---
- name: Download OpenShift CLI
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
    dest: /tmp/oc.tar.gz

- name: Extract OpenShift CLI
  unarchive:
    src: /tmp/oc.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Ensure oc is executable
  file:
    path: /usr/local/bin/oc
    mode: '0755'
    state: file

