---

- name: Install MySQL and Configure Database
  hosts: web 
  become: true
  vars_files:
    - secret.yml
    - secrett.yml
  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present
        
    - name: Install MySQL Python library
      apt:
        name: python3-pymysql
        state: present


    - name: Enable and Start MySQL Service
      service:
        name: mysql
        enabled: yes
        state: started
    

    - name: Create Database
      mysql_db:
        name: mydbd
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create user with differente permissions to different databases
      mysql_user:
        login_user: admin
        login_password: admin
        name: demo
        state: present
        priv: "mydbd.*:INSERT,UPDATE/anotherdb.*:SELECT/yetanotherdb.*:ALL"


    - name: Create MySQL User
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        state: present

    - name: Grant Privileges to User on Database
      mysql_user:
        name: "{{ mysql_user }}"
        priv: "mydbd.*:ALL"
        state: present

  
