apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: lab11
subjects:
- kind: ServiceAccount
  name: pod-reader-sa
  namespace: lab11
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

