@Library('Jowe-shared-library') _
pipeline {
    agent {
        label 'slave'
        
    }
    stages{
        stage (DockerBuild){
        steps{
                                 buildDockerImage("ivolveimg")  
            }
        }

        stage(OpenshiftDeployment){
            steps{
                                openshiftDeployment("omaryousef/ivolveimg")
            }
        }
    }
    
}
