@Library('Jowe-shared-library') _
pipeline {
    agent {
        label 'slave'
        
    }
    stages{
        stage (DockerBuild){
        steps{
                                 buildDockerImage("ivolveimg")  
            }
        }

        stage('Push image to Docker hub') {
            steps {
                script {
                 	
                 		pushDockerImage("${dockerHubCredentialsID}", "${imageName}")
                      
                }
            }
        }

        stage(OpenshiftDeployment){
            steps{
                                openshiftDeployment("omaryousef/ivolveimg")
            }
        }
    }
    
}
