@Library('Jowe-shared-library') _
pipeline {
    agent {
        label 'slave'
        
    }
    stages{
        stage (DockerBuild){
        steps{
                                 buildDockerImage("newlab")  
            }
        }

        stage(Dockerpush){
            steps{
                                pushDockerImage("newlab")
            }
        }

        stage(OpenshiftDeployment){
            steps{
                                openshiftDeployment("omaryousef/newlab")
            }
        }
    }
    
}
